name = "fuzhou-fishery-expo"
main = "./_worker.js"
compatibility_date = "2026-03-20"

[observability]
enabled = true
head_sampling_rate = 1

[secrets]
required = ["JWT_SECRET"]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/*"]

[vars]
CONFIRMATION_PUBLIC_ORIGIN = "https://expo.chinafife.com/Exhibitors-confirmation"

[[d1_databases]]
binding = "DB"
database_name = "exhibition_db"
database_id = "c190ca96-3fa2-48bf-aade-0b995f4f02bd"

[[kv_namespaces]]
binding = "CACHE"
id = "a26f48b31c124eb6a0f0fc9274134a02"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "expo-contracts"
